version: "3.7"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/vol01/Docker/monitoring
  influxdb:
    image: arm64v8/influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin #Admin username
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123 #Admin password
      - DOCKER_INFLUXDB_INIT_ORG=admin
      - DOCKER_INFLUXDB_INIT_BUCKET=tesla #Changing this would require also changing it in the Grafana dashboard file.
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token #Change this to something secure - this links to Grafana with username specified above
  polly:
    image: averysmalldog/tesla-gen3wc-monitor
    container_name: polly
    restart: always
    networks:
      - monitoring
    environment: 
      - HPWC_IP=10.0.0.5 #Set this IP to the Wall Connector
      - INFLUX_IP=host.docker.internal #Set this IP to point to the Docker container
    depends_on:
      - influxdb
networks:
  monitoring:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
